services:
  db:
    container_name: db-prod
    image: postgres:18-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 10s
      interval: 5s
      retries: 5
    networks:
      - network-default
    restart: unless-stopped
    env_file:
      - .env

  redis:
    container_name: redis-prod
    image: redis:7-alpine
    ports:
      - "127.0.0.1:${REDIS_PORT:-6380}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - network-default
    restart: unless-stopped
    env_file:
      - .env

  web:
    container_name: web-prod
    build: .
    entrypoint: /app/scripts/entrypoint.sh
    volumes:
      - app_data:/app/cdn
    ports:
      - "127.0.0.1:${APP_PORT:-8000}:8000"
    healthcheck:
      test: [ "CMD-SHELL", "./scripts/healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network-default
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  worker:
    container_name: worker-prod
    build: .
    command: python -m celery -A config worker --loglevel=INFO
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network-default
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  beat:
    container_name: beat-prod
    build: .
    command: python -m celery -A config beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network-default
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

volumes:
  app_data:
    name: rent_market_app_data

networks:
  network-default:
    driver: bridge
